// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerC0PNTxU_gxUq31N5tNkxOW6LyjQLac',
    appId: '1:361362848559:android:daa4437b646366a0ccffda',
    messagingSenderId: '361362848559',
    projectId: 'guardianarea-69611',
    storageBucket: 'guardianarea-69611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxcMNz0H4ElmQykhwL-6QnBbMUq5sHD3Y',
    appId: '1:361362848559:ios:a17117a817556598ccffda',
    messagingSenderId: '361362848559',
    projectId: 'guardianarea-69611',
    storageBucket: 'guardianarea-69611.firebasestorage.app',
    iosBundleId: 'com.digitaldart.guardianArea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfm2Wk8M6SO7EqwPWxGQx_BzC8TE3_URI',
    appId: '1:361362848559:web:37a5653dc8051085ccffda',
    messagingSenderId: '361362848559',
    projectId: 'guardianarea-69611',
    authDomain: 'guardianarea-69611.firebaseapp.com',
    storageBucket: 'guardianarea-69611.firebasestorage.app',
    measurementId: 'G-70QS38D5PV',
  );
}
